# Generated by Django 3.0 on 2019-12-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='result',
            field=models.BooleanField(default=False, verbose_name='result'),
        ),
        migrations.AddField(
            model_name='invite',
            name='result',
            field=models.BooleanField(default=False, verbose_name='result'),
        ),
        migrations.AlterField(
            model_name='user',
            name='isFreezed',
            field=models.BooleanField(default=False, verbose_name='isFreezed'),
        ),
        migrations.AlterField(
            model_name='user',
            name='isVerificated',
            field=models.BooleanField(default=False, verbose_name='isVerificated'),
        ),
    ]
