# Generated by Django 3.0 on 2019-12-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEsite', '0002_auto_20191221_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message2Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('userId', models.IntegerField(verbose_name='userId')),
                ('content', models.TextField(verbose_name='content')),
                ('pushTime', models.DateField(auto_now_add=True, verbose_name='pushTime')),
            ],
        ),
        migrations.CreateModel(
            name='Message2User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('userId', models.IntegerField(verbose_name='userId')),
                ('content', models.TextField(verbose_name='content')),
                ('pushTime', models.DateField(auto_now_add=True, verbose_name='pushTime')),
                ('isSend', models.BooleanField(default=False, verbose_name='isSend')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='isPushed',
            field=models.BooleanField(default=False, verbose_name='isPushed'),
        ),
    ]
