# Generated by Django 3.0 on 2019-12-22 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SEsite', '0003_auto_20191222_0958'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message2Project',
        ),
    ]
