# Generated by Django 3.0 on 2019-12-22 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SEsite', '0004_delete_message2project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
