# Generated by Django 3.0 on 2019-12-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEsite', '0006_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='message2user',
            name='fromWho',
            field=models.TextField(default='admin', verbose_name='content'),
        ),
    ]
