# Generated by Django 3.0 on 2019-12-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEsite', '0007_message2user_fromwho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message2user',
            name='fromWho',
            field=models.CharField(max_length=12, verbose_name='content'),
        ),
    ]
