# Generated by Django 3.0 on 2019-12-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEsite', '0009_project_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('isUser', models.BooleanField(default=True, verbose_name='isUser')),
                ('userId', models.IntegerField(verbose_name='userId')),
                ('projectId', models.IntegerField(verbose_name='projectId')),
                ('content', models.TextField(verbose_name='content')),
                ('fromWho', models.CharField(max_length=12, verbose_name='fromWho')),
                ('pushTime', models.DateField(auto_now_add=True, verbose_name='pushTime')),
                ('isSend', models.BooleanField(default=False, verbose_name='isSend')),
            ],
        ),
        migrations.DeleteModel(
            name='Message2User',
        ),
    ]
