# Generated by Django 3.0 on 2019-12-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEsite', '0010_auto_20191223_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('isUser', models.BooleanField(default=True, verbose_name='isUser')),
                ('userId', models.IntegerField(verbose_name='userId')),
                ('projectId', models.IntegerField(verbose_name='projectId')),
                ('file', models.FileField(upload_to='', verbose_name='file')),
            ],
        ),
    ]
