# Generated by Django 3.0 on 2019-12-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEsite', '0011_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='name',
            field=models.CharField(default='null.null', max_length=120, verbose_name='name'),
        ),
    ]
