# Generated by Django 3.0 on 2019-12-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEsite', '0012_repository_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(default='null', max_length=120, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='projectId',
            field=models.IntegerField(default=0, verbose_name='projectId'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='userId',
            field=models.IntegerField(default=0, verbose_name='userId'),
        ),
    ]
