# Generated by Django 3.0 on 2019-12-23 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEsite', '0013_auto_20191223_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='file',
            field=models.FileField(upload_to='file/', verbose_name='file'),
        ),
    ]
