# Generated by Django 3.0 on 2019-12-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEsite', '0014_auto_20191223_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('taskId', models.IntegerField(verbose_name='taskId')),
                ('name', models.CharField(max_length=12, verbose_name='name')),
                ('content', models.TextField(verbose_name='content')),
                ('file', models.FileField(upload_to='file/', verbose_name='file')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='code',
            field=models.CharField(default='', max_length=12, verbose_name='code'),
        ),
    ]
