# Generated by Django 3.0 on 2019-12-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEsite', '0015_auto_20191223_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='nameProject',
            field=models.CharField(default='', max_length=12, verbose_name='name'),
        ),
    ]
