# Generated by Django 3.0 on 2019-12-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEsite', '0016_task_nameproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='userId',
            field=models.IntegerField(default=0, verbose_name='userId'),
        ),
    ]
