# Generated by Django 3.0 on 2019-12-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEsite', '0017_commit_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='file',
            field=models.FileField(upload_to='commit/', verbose_name='file'),
        ),
    ]
