# Generated by Django 3.0 on 2019-12-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEsite', '0018_auto_20191223_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='username',
            field=models.CharField(default='', max_length=12, verbose_name='name'),
        ),
    ]
