# Generated by Django 3.0 on 2019-12-23 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SEsite', '0019_commit_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='commitTime',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='commitTime'),
        ),
    ]
