# Generated by Django 3.0 on 2019-12-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEsite', '0020_commit_committime'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='userName',
            field=models.CharField(default='null', max_length=12, verbose_name='userName'),
            preserve_default=False,
        ),
    ]
