# Generated by Django 3.0 on 2019-12-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEsite', '0021_apply_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='check',
            field=models.BooleanField(default=False, verbose_name='check'),
        ),
        migrations.AddField(
            model_name='invite',
            name='check',
            field=models.BooleanField(default=False, verbose_name='check'),
        ),
    ]
